# Generated by Django 2.0.1 on 2018-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='unknown', max_length=250),
        ),
    ]
